/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SchoolManagementSystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);// center form in d screen

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jtxtStudentinfo1 = new javax.swing.JButton();
        jtxtSr1 = new javax.swing.JButton();
        jtxtTI1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtLs1 = new javax.swing.JButton();
        jtxtStudentfee2 = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        Parents2 = new javax.swing.JButton();
        Parents3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtStudentinfo = new javax.swing.JButton();
        jtxtSr = new javax.swing.JButton();
        jtxtTI = new javax.swing.JButton();
        jtxtLs = new javax.swing.JButton();
        jtxtStudentfee1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        student = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        Parents1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Main Menu");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 19, -1, -1));

        jtxtStudentinfo1.setBackground(new java.awt.Color(0, 0, 255));
        jtxtStudentinfo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtStudentinfo1.setForeground(new java.awt.Color(255, 255, 0));
        jtxtStudentinfo1.setText("Student  Information");
        jtxtStudentinfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentinfo1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jtxtStudentinfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 217, -1));

        jtxtSr1.setBackground(new java.awt.Color(0, 0, 255));
        jtxtSr1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtSr1.setForeground(new java.awt.Color(255, 255, 0));
        jtxtSr1.setText("Student_ Records");
        jtxtSr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSr1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jtxtSr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 217, -1));

        jtxtTI1.setBackground(new java.awt.Color(0, 0, 255));
        jtxtTI1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtTI1.setForeground(new java.awt.Color(255, 255, 0));
        jtxtTI1.setText("Teacher's Information");
        jtxtTI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTI1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jtxtTI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 177, 248, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("Choose from the Options");
        jFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 79, -1, -1));

        jtxtLs1.setBackground(new java.awt.Color(0, 0, 255));
        jtxtLs1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtLs1.setForeground(new java.awt.Color(255, 255, 0));
        jtxtLs1.setText("Library System");
        jtxtLs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLs1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jtxtLs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 217, -1));

        jtxtStudentfee2.setBackground(new java.awt.Color(0, 0, 255));
        jtxtStudentfee2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtStudentfee2.setForeground(new java.awt.Color(255, 255, 0));
        jtxtStudentfee2.setText("Student's Fee Submission");
        jtxtStudentfee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentfee2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jtxtStudentfee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 110, 248, -1));

        Exit1.setBackground(new java.awt.Color(0, 0, 255));
        Exit1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit1.setForeground(new java.awt.Color(255, 255, 0));
        Exit1.setText("Exit");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 382, 81, -1));

        Parents2.setBackground(new java.awt.Color(0, 0, 255));
        Parents2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Parents2.setForeground(new java.awt.Color(255, 255, 0));
        Parents2.setText("Salary ");
        Parents2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parents2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(Parents2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 327, 248, -1));

        Parents3.setBackground(new java.awt.Color(0, 0, 255));
        Parents3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Parents3.setForeground(new java.awt.Color(255, 255, 0));
        Parents3.setText("Parent Form");
        Parents3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parents3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(Parents3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 251, 248, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Main Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 19, -1, -1));

        jtxtStudentinfo.setBackground(new java.awt.Color(0, 0, 255));
        jtxtStudentinfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtStudentinfo.setForeground(new java.awt.Color(255, 255, 0));
        jtxtStudentinfo.setText("Student  Information");
        jtxtStudentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentinfoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtStudentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 240, -1));

        jtxtSr.setBackground(new java.awt.Color(0, 0, 255));
        jtxtSr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtSr.setForeground(new java.awt.Color(255, 255, 0));
        jtxtSr.setText("Student Results");
        jtxtSr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSrActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtSr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, -1));

        jtxtTI.setBackground(new java.awt.Color(0, 0, 255));
        jtxtTI.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtTI.setForeground(new java.awt.Color(255, 255, 0));
        jtxtTI.setText("Teacher's Information");
        jtxtTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTIActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 248, -1));

        jtxtLs.setBackground(new java.awt.Color(0, 0, 255));
        jtxtLs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtLs.setForeground(new java.awt.Color(255, 255, 0));
        jtxtLs.setText("Library System");
        jtxtLs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtLs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 240, -1));

        jtxtStudentfee1.setBackground(new java.awt.Color(0, 0, 255));
        jtxtStudentfee1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtStudentfee1.setForeground(new java.awt.Color(255, 255, 0));
        jtxtStudentfee1.setText("Student Fee ");
        jtxtStudentfee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentfee1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtStudentfee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 248, -1));

        Exit.setBackground(new java.awt.Color(0, 0, 255));
        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 0));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 81, -1));

        student.setBackground(new java.awt.Color(0, 0, 255));
        student.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        student.setForeground(new java.awt.Color(255, 255, 0));
        student.setText("Student Reg..");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        getContentPane().add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 240, -1));

        Admin.setBackground(new java.awt.Color(0, 0, 255));
        Admin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 0));
        Admin.setText("Admin..");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 248, -1));

        Parents1.setBackground(new java.awt.Color(0, 0, 255));
        Parents1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Parents1.setForeground(new java.awt.Color(255, 255, 0));
        Parents1.setText("Parent Form");
        Parents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Parents1ActionPerformed(evt);
            }
        });
        getContentPane().add(Parents1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 248, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Choose from the Options");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtStudentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentinfoActionPerformed
StudentInformation m = new StudentInformation();
m.setVisible(true);
this.dispose();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentinfoActionPerformed

    private void jtxtSrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSrActionPerformed

Student_Results m = new Student_Results();
m.setVisible(true);
this.dispose();
    
// TODO add your handling code here:
    }//GEN-LAST:event_jtxtSrActionPerformed

    private void jtxtTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTIActionPerformed
TeachersInformation m = new  TeachersInformation();
m.setVisible(true);
this.dispose();
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTIActionPerformed

    private void jtxtLsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLsActionPerformed
LibrarySystem m = new LibrarySystem();
m.setVisible(true);
this.dispose();
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLsActionPerformed

    private void jtxtStudentfee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentfee1ActionPerformed
StudentFee1 m = new StudentFee1();
m.setVisible(true);
this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentfee1ActionPerformed
private JFrame frame;
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    
        frame =new JFrame();
    if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","School Management Systems",
       JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION)
    {
       System.exit(0);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed
StudentsRegistration m = new StudentsRegistration();
m.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_studentActionPerformed

    private void jtxtStudentinfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentinfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentinfo1ActionPerformed

    private void jtxtSr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSr1ActionPerformed

    private void jtxtTI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTI1ActionPerformed

    private void jtxtLs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLs1ActionPerformed

    private void jtxtStudentfee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentfee2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentfee2ActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit1ActionPerformed

    private void Parents2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parents2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parents2ActionPerformed

    private void Parents3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parents3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Parents3ActionPerformed

    private void Parents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Parents1ActionPerformed
ParentForm m = new ParentForm();
m.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Parents1ActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        Admin m = new Admin();
        m.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Exit1;
    private javax.swing.JButton Parents1;
    private javax.swing.JButton Parents2;
    private javax.swing.JButton Parents3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jtxtLs;
    private javax.swing.JButton jtxtLs1;
    private javax.swing.JButton jtxtSr;
    private javax.swing.JButton jtxtSr1;
    private javax.swing.JButton jtxtStudentfee1;
    private javax.swing.JButton jtxtStudentfee2;
    private javax.swing.JButton jtxtStudentinfo;
    private javax.swing.JButton jtxtStudentinfo1;
    private javax.swing.JButton jtxtTI;
    private javax.swing.JButton jtxtTI1;
    private javax.swing.JButton student;
    // End of variables declaration//GEN-END:variables
}
