/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SchoolManagementSystem;
//import java.util.Calender;
//import java.util.GregorianCalender;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class StudentFee1 extends javax.swing.JFrame {
private JFrame frame;
    /**
     * Creates new form StudentFee1
     */
    public StudentFee1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtStudent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtFN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtCN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FeeDetails = new javax.swing.JComboBox();
        Class = new javax.swing.JComboBox();
        Gen = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Paidamount = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Bn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        Insert = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3), "Student's Fee Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Student ID:");

        jtxtStudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStudentActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Name:");

        jtxtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Father's Name:");

        jtxtFN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Class:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Phone No:");

        jtxtCN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Fees Detail:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Gender:");

        jArea.setColumns(20);
        jArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jArea.setRows(5);
        jScrollPane2.setViewportView(jArea);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Paid Amount:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Select Day/Month:");

        FeeDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FeeDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "Admission fee", "Monthly fee", "Examination fee" }));
        FeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeeDetailsActionPerformed(evt);
            }
        });

        Class.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Class.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "pr1", "pr2", "pr3", "pr4", "pr5" }));
        Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassActionPerformed(evt);
            }
        });

        Gen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Gen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "F", "M" }));

        Paidamount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Paidamount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "500000", "100000", "150000" }));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Bank No:");

        Bn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtStudent)
                    .addComponent(jtxtName)
                    .addComponent(jtxtFN)
                    .addComponent(Class, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtCN)
                    .addComponent(FeeDetails, 0, 0, Short.MAX_VALUE)
                    .addComponent(Gen, 0, 154, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Paidamount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtxtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtxtCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(FeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Paidamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Bn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 750, 510));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "FatherName", "Class", "phoneNo", "FeeDetail", "Gender", "SelectMonth", "PaidAmonut", "BankNo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 750, 110));

        Update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, -1));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, -1, -1));

        Reset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, -1, -1));

        Menu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, -1, -1));

        Insert.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        Delete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStudentActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFNActionPerformed

    private void jtxtCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCNActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
if(jTable1.getSelectedRow() == -1)
{
    if (jTable1.getRowCount() == 0)
    {
        JOptionPane.showMessageDialog(null, "No data to delete","Student Fee Systems",
                         JOptionPane.OK_OPTION);
    }else{
       
    
        JOptionPane.showMessageDialog(null, "Select a row to  delete","Student Fee Systems",
                         JOptionPane.OK_OPTION);
    }
    
}else
{
    model.removeRow(jTable1.getSelectedRow());
} 


        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
frame =new JFrame();
    if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Student Fee Systems",
       JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION)
    {
       System.exit(0);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
   JTextField temp = null;
   for (Component c:jPanel1.getComponents())
{
    if(c.getClass().toString().contains("javax.swing.JTextField"))
    {
        temp = (JTextField)c;
        temp.setText(null);
    }
       Class.getModel().setSelectedItem("Select");
       FeeDetails.getModel().setSelectedItem("Select");
       //jMonthChooser1.getMonth();
       Gen.getModel().setSelectedItem("Select");
       jDateChooser1.getDate();
       Paidamount.getModel().setSelectedItem("Select");
       jArea.setText("");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
       MainMenu l=new MainMenu();
       l.setVisible(true);
       this.dispose();
       l.setVisible(true);
       this.dispose();  

        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
//SimpleDateFormat tTime new SimpleDateFormat("HH:mm:ss");
//tTime.format(timer.getTime());
JOptionPane.showMessageDialog(rootPane, "All your Data has been saved");
        
       
 String Qty12 = "";     
     
if(Paidamount.getSelectedItem().equals("500000"))
     {
         Qty12 = "500000";
     
     }
     else if(Paidamount.getSelectedItem().equals("100000"))
     {
         Qty12 = "100000";
     }
     else if(Paidamount.getSelectedItem().equals("150000"))
     {
         Qty12 = "150000";
     }
     
        String Qty13 = "";     
     
     if(FeeDetails.getSelectedItem().equals("Admission fee"))
     {
         Qty13 = "Admission fee";
     
     }
     else if(FeeDetails.getSelectedItem().equals("Monthly fee"))
     {
         Qty13 = "Monthly fee";
     }
     else if(FeeDetails.getSelectedItem().equals("Examination fee"))
     {
         Qty13 = "Examination fee";
     }
     
     String Qty14 = "";     
     
     if(Class.getSelectedItem().equals("pr1"))
     {
          Qty14 = "pr1";
     
     }
     else if(Class.getSelectedItem().equals("pr2"))
     {
         Qty14= "pr2";
     }
     else if(Class.getSelectedItem().equals("pr3"))
     {
         Qty14 = "pr3";
     }
      else if(Class.getSelectedItem().equals("pr4"))
     {
         Qty14 = "pr4";
     }
     else if(Class.getSelectedItem().equals("pr5"))
     {
         Qty14 = "pr5";
     }
 
 
    
     
     String Qty17 = "";     
     
     if(Gen.getSelectedItem().equals("F"))
     {
          Qty17 = "F";
     
     }
     else if(Gen.getSelectedItem().equals("M"))
     {
         Qty17= "M";
     }
        
     
     
     jArea.append("Student Fee Systems\n"
        +"===============================\n"
        +"\nStudent ID:\t\t" +jtxtStudent.getText()
        +"\nName:\t\t\t" +jtxtName.getText()
        +"\nFather Name:\t\t" +jtxtFN.getText() 
        +"\nClass:\t\t\t" +Qty14
        +"\nContact No:\t\t" +jtxtCN.getText()
        +"\nFee Details:\t\t" +Qty13
        //+"\nSelect Month:\t\t" +jMonthChooser1.getMonth()
        +"\nGender :\t\t" +Qty17
        +"\nSelect Day/Month:\t" +jDateChooser1.getDate()
        +"\nPaid Amount:\t\t" +Qty12
        +"\nBank No:\t\t"+Bn.getText()
         +"\n"    
        );
    


        // TODO add your handling code here:
    }//GEN-LAST:event_InsertActionPerformed

    private void FeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeeDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeeDetailsActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[]{jtxtStudent.getText() ,jtxtName.getText(),jtxtFN.getText(),
Class.getSelectedItem().toString(),jtxtCN.getText(),FeeDetails.getSelectedItem().toString(),
Gen.getSelectedItem().toString(),jDateChooser1.getDate().toString(),Paidamount.getSelectedItem().toString(),Bn.getText()});

        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFee1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFee1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bn;
    private javax.swing.JComboBox Class;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox FeeDetails;
    private javax.swing.JComboBox Gen;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Menu;
    private javax.swing.JComboBox Paidamount;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Update;
    private javax.swing.JTextArea jArea;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtCN;
    private javax.swing.JTextField jtxtFN;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtStudent;
    // End of variables declaration//GEN-END:variables
}
