/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SchoolManagementSystem;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TeachersInformation extends javax.swing.JFrame {
 private JFrame frame; 
    /**
     * Creates new form TeachersInformation
     */
    public TeachersInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtFN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtEdu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtCN1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtCN2 = new javax.swing.JTextField();
        Gen = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jtxtCA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtNS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtGen = new javax.swing.JTextField();
        jbtnUpdate = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnMenu = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 3), "Teacher's Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Teachers ID:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("First name:");

        jtxtFN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Surname:");

        jtxtSN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Email");

        jtxtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Education:");

        jtxtEdu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEduActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Phone No 1:");

        jtxtCN1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCN1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Phone No 2:");

        jtxtCN2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCN2ActionPerformed(evt);
            }
        });

        Gen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Gen.setText("Gender:");

        jComboBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Class:");

        jtxtCA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCAActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Contact Address:");

        jtxtC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("No of Students:");

        jtxtNS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNSActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TeachersID", "Firstname", "Surname", "Email", "Education", "phoneno1", "phoneno2", "Class", "NoofStudents", "ContactAddress", "Gender"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jtxtGen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(Gen)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtCA)
                    .addComponent(jtxtNS)
                    .addComponent(jtxtC)
                    .addComponent(jtxtGen)
                    .addComponent(jtxtCN2)
                    .addComponent(jtxtCN1)
                    .addComponent(jtxtEdu)
                    .addComponent(jtxtEmail)
                    .addComponent(jtxtSN)
                    .addComponent(jtxtFN)
                    .addComponent(jComboBox, 0, 176, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtCN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtCN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gen)
                    .addComponent(jtxtGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtxtCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1180, 620));

        jbtnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 140, -1));

        jbtnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 640, 100, -1));

        jbtnMenu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnMenu.setText("Menu");
        jbtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 640, 120, -1));

        jbtnReset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 640, 130, -1));

        jbtnDelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFNActionPerformed

    private void jtxtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSNActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEduActionPerformed

    private void jtxtCN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCN1ActionPerformed

    private void jtxtCN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCN2ActionPerformed

    private void jtxtCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCAActionPerformed

    private void jtxtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCActionPerformed

    private void jtxtNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNSActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
frame =new JFrame();
    if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Teachers Information Systems",
       JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION)
    {
       System.exit(0);
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
   JTextField temp = null;
   for (Component c:jPanel1.getComponents())
{
    if(c.getClass().toString().contains("javax.swing.JTextField"))
    {
        temp = (JTextField)c;
        temp.setText(null);
    }
    jComboBox.getModel().setSelectedItem("Select");
    

}

        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuActionPerformed

       MainMenu l=new MainMenu();
       l.setVisible(true);
       this.dispose();
       l.setVisible(true);
       this.dispose();  
// TODO add your handling code here:
    }//GEN-LAST:event_jbtnMenuActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
    JOptionPane.showMessageDialog(rootPane, "All your Data has been saved");

    DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{ jComboBox.getSelectedItem().toString(),
    jtxtFN.getText(),jtxtSN.getText(),jtxtEmail.getText(),jtxtEdu.getText(),
    jtxtCN1.getText(),jtxtCN2.getText(),jtxtC.getText(),jtxtNS.getText(),
    jtxtCA.getText(),jtxtGen.getText(),});

        {
       
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
if (jComboBox.getSelectedItem().equals("1"))
        {
            jtxtFN.setText("chidinma");
            jtxtSN.setText("Nwabueze");
            jtxtEmail.setText("chidi@gmail.com");
            jtxtEdu.setText("Bsc");
            jtxtCN1.setText("081234675");
            jtxtCN2.setText("090678932");
            jtxtGen.setText("F");
            jtxtC.setText(" 4");
            jtxtNS.setText("20");
            jtxtCA.setText("101 road festac town");
            
    }
        else if(jComboBox.getSelectedItem().equals("2"))
        {
            jtxtFN.setText("Blessing");
            jtxtSN.setText("Erogbare");
            jtxtEmail.setText("Blessero@yahoo.com");
            jtxtEdu.setText("Btech");
            jtxtCN1.setText("080234567");
            jtxtCN2.setText("081567893");
            jtxtGen.setText("F");
            jtxtC.setText("Elementary");
            jtxtNS.setText("21");
            jtxtCA.setText("15,oluwadare street,palmgroove");
            
            
           
        }
 else if(jComboBox.getSelectedItem().equals("3"))
        {
            jtxtFN.setText("Biodun");
            jtxtSN.setText("Adigun");
            jtxtEmail.setText("Adgun23@yahoo.com");
            jtxtEdu.setText("Bsc");
            jtxtCN1.setText("0807654542");
            jtxtCN2.setText("090345762");
            jtxtGen.setText("M");
            jtxtC.setText(" 6");
            jtxtNS.setText("25");
            jtxtCA.setText("5b,carnal estate Amuwo-Odofin");
            
           
        }
        else if(jComboBox.getSelectedItem().equals("Select"))
        {jtxtFN.setText("");
            jtxtSN.setText("");
            jtxtEmail.setText("");
            jtxtEdu.setText("");
            jtxtCN1.setText("");
            jtxtCN2.setText("");
            jtxtGen.setText("");
            jtxtC.setText("");
            jtxtNS.setText("");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxtGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGenActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
if(jTable1.getSelectedRow() == -1)
{
    if (jTable1.getRowCount() == 0)
    {
        JOptionPane.showMessageDialog(null, "No data to delete","Teachers Information Systems",
                         JOptionPane.OK_OPTION);
    }else{
       
    
        JOptionPane.showMessageDialog(null, "Select a row to  delete","Teachers Information Systems",
                         JOptionPane.OK_OPTION);
    }
    
}else
{
    model.removeRow(jTable1.getSelectedRow());
} 


        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnMenu;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtC;
    private javax.swing.JTextField jtxtCA;
    private javax.swing.JTextField jtxtCN1;
    private javax.swing.JTextField jtxtCN2;
    private javax.swing.JTextField jtxtEdu;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFN;
    private javax.swing.JTextField jtxtGen;
    private javax.swing.JTextField jtxtNS;
    private javax.swing.JTextField jtxtSN;
    // End of variables declaration//GEN-END:variables
}

